//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplication.BankAppServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Musteri", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Musteri : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MusteriIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TcNumarasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EpostaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MusteriID {
            get {
                return this.MusteriIDField;
            }
            set {
                if ((this.MusteriIDField.Equals(value) != true)) {
                    this.MusteriIDField = value;
                    this.RaisePropertyChanged("MusteriID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TcNumarasi {
            get {
                return this.TcNumarasiField;
            }
            set {
                if ((object.ReferenceEquals(this.TcNumarasiField, value) != true)) {
                    this.TcNumarasiField = value;
                    this.RaisePropertyChanged("TcNumarasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Soyadi {
            get {
                return this.SoyadiField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadiField, value) != true)) {
                    this.SoyadiField = value;
                    this.RaisePropertyChanged("Soyadi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Eposta {
            get {
                return this.EpostaField;
            }
            set {
                if ((object.ReferenceEquals(this.EpostaField, value) != true)) {
                    this.EpostaField = value;
                    this.RaisePropertyChanged("Eposta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hesap", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Hesap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HesapIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HesapNoField;
        
        private decimal BakiyeField;
        
        private bool IsOpenField;
        
        private int MusteriIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HesapID {
            get {
                return this.HesapIDField;
            }
            set {
                if ((this.HesapIDField.Equals(value) != true)) {
                    this.HesapIDField = value;
                    this.RaisePropertyChanged("HesapID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HesapNo {
            get {
                return this.HesapNoField;
            }
            set {
                if ((object.ReferenceEquals(this.HesapNoField, value) != true)) {
                    this.HesapNoField = value;
                    this.RaisePropertyChanged("HesapNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Bakiye {
            get {
                return this.BakiyeField;
            }
            set {
                if ((this.BakiyeField.Equals(value) != true)) {
                    this.BakiyeField = value;
                    this.RaisePropertyChanged("Bakiye");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IsOpen {
            get {
                return this.IsOpenField;
            }
            set {
                if ((this.IsOpenField.Equals(value) != true)) {
                    this.IsOpenField = value;
                    this.RaisePropertyChanged("IsOpen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int MusteriID {
            get {
                return this.MusteriIDField;
            }
            set {
                if ((this.MusteriIDField.Equals(value) != true)) {
                    this.MusteriIDField = value;
                    this.RaisePropertyChanged("MusteriID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankAppServiceReference.BankWebServiceSoap")]
    public interface BankWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCustomer", ReplyAction="*")]
        BankApplication.BankAppServiceReference.AddCustomerResponse AddCustomer(BankApplication.BankAppServiceReference.AddCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.AddCustomerResponse> AddCustomerAsync(BankApplication.BankAppServiceReference.AddCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name GetCustomerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomer", ReplyAction="*")]
        BankApplication.BankAppServiceReference.GetCustomerResponse GetCustomer(BankApplication.BankAppServiceReference.GetCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.GetCustomerResponse> GetCustomerAsync(BankApplication.BankAppServiceReference.GetCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name item from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        BankApplication.BankAppServiceReference.UpdateCustomerResponse UpdateCustomer(BankApplication.BankAppServiceReference.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.UpdateCustomerResponse> UpdateCustomerAsync(BankApplication.BankAppServiceReference.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        void DeleteCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteCustomerAsync(int id);
        
        // CODEGEN: Generating message contract since element name TcNumarasi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        BankApplication.BankAppServiceReference.LoginResponse Login(BankApplication.BankAppServiceReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.LoginResponse> LoginAsync(BankApplication.BankAppServiceReference.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name OpenAccountResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OpenAccount", ReplyAction="*")]
        BankApplication.BankAppServiceReference.OpenAccountResponse OpenAccount(BankApplication.BankAppServiceReference.OpenAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OpenAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.OpenAccountResponse> OpenAccountAsync(BankApplication.BankAppServiceReference.OpenAccountRequest request);
        
        // CODEGEN: Generating message contract since element name hesapNumarasi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CloseAccount", ReplyAction="*")]
        BankApplication.BankAppServiceReference.CloseAccountResponse CloseAccount(BankApplication.BankAppServiceReference.CloseAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CloseAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.CloseAccountResponse> CloseAccountAsync(BankApplication.BankAppServiceReference.CloseAccountRequest request);
        
        // CODEGEN: Generating message contract since element name ListAccountsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAccounts", ReplyAction="*")]
        BankApplication.BankAppServiceReference.ListAccountsResponse ListAccounts(BankApplication.BankAppServiceReference.ListAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAccounts", ReplyAction="*")]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.ListAccountsResponse> ListAccountsAsync(BankApplication.BankAppServiceReference.ListAccountsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTransfer", ReplyAction="*")]
        void SendTransfer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendTransfer", ReplyAction="*")]
        System.Threading.Tasks.Task SendTransferAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendVirman", ReplyAction="*")]
        void SendVirman();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendVirman", ReplyAction="*")]
        System.Threading.Tasks.Task SendVirmanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        void GetCredit();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        System.Threading.Tasks.Task GetCreditAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNumber", ReplyAction="*")]
        int CreateNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CreateNumberAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCustomer", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.AddCustomerRequestBody Body;
        
        public AddCustomerRequest() {
        }
        
        public AddCustomerRequest(BankApplication.BankAppServiceReference.AddCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankApplication.BankAppServiceReference.Musteri item;
        
        public AddCustomerRequestBody() {
        }
        
        public AddCustomerRequestBody(BankApplication.BankAppServiceReference.Musteri item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.AddCustomerResponseBody Body;
        
        public AddCustomerResponse() {
        }
        
        public AddCustomerResponse(BankApplication.BankAppServiceReference.AddCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddCustomerResponseBody {
        
        public AddCustomerResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomer", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.GetCustomerRequestBody Body;
        
        public GetCustomerRequest() {
        }
        
        public GetCustomerRequest(BankApplication.BankAppServiceReference.GetCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCustomerRequestBody() {
        }
        
        public GetCustomerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.GetCustomerResponseBody Body;
        
        public GetCustomerResponse() {
        }
        
        public GetCustomerResponse(BankApplication.BankAppServiceReference.GetCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankApplication.BankAppServiceReference.Musteri GetCustomerResult;
        
        public GetCustomerResponseBody() {
        }
        
        public GetCustomerResponseBody(BankApplication.BankAppServiceReference.Musteri GetCustomerResult) {
            this.GetCustomerResult = GetCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomer", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.UpdateCustomerRequestBody Body;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(BankApplication.BankAppServiceReference.UpdateCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankApplication.BankAppServiceReference.Musteri item;
        
        public UpdateCustomerRequestBody() {
        }
        
        public UpdateCustomerRequestBody(BankApplication.BankAppServiceReference.Musteri item) {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.UpdateCustomerResponseBody Body;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(BankApplication.BankAppServiceReference.UpdateCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCustomerResponseBody {
        
        public UpdateCustomerResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(BankApplication.BankAppServiceReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TcNumarasi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Sifre;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string TcNumarasi, string Sifre) {
            this.TcNumarasi = TcNumarasi;
            this.Sifre = Sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(BankApplication.BankAppServiceReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(int LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenAccount", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.OpenAccountRequestBody Body;
        
        public OpenAccountRequest() {
        }
        
        public OpenAccountRequest(BankApplication.BankAppServiceReference.OpenAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OpenAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public OpenAccountRequestBody() {
        }
        
        public OpenAccountRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OpenAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.OpenAccountResponseBody Body;
        
        public OpenAccountResponse() {
        }
        
        public OpenAccountResponse(BankApplication.BankAppServiceReference.OpenAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OpenAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankApplication.BankAppServiceReference.Hesap OpenAccountResult;
        
        public OpenAccountResponseBody() {
        }
        
        public OpenAccountResponseBody(BankApplication.BankAppServiceReference.Hesap OpenAccountResult) {
            this.OpenAccountResult = OpenAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloseAccount", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.CloseAccountRequestBody Body;
        
        public CloseAccountRequest() {
        }
        
        public CloseAccountRequest(BankApplication.BankAppServiceReference.CloseAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CloseAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hesapNumarasi;
        
        public CloseAccountRequestBody() {
        }
        
        public CloseAccountRequestBody(int id, string hesapNumarasi) {
            this.id = id;
            this.hesapNumarasi = hesapNumarasi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CloseAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.CloseAccountResponseBody Body;
        
        public CloseAccountResponse() {
        }
        
        public CloseAccountResponse(BankApplication.BankAppServiceReference.CloseAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CloseAccountResponseBody {
        
        public CloseAccountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAccountsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAccounts", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.ListAccountsRequestBody Body;
        
        public ListAccountsRequest() {
        }
        
        public ListAccountsRequest(BankApplication.BankAppServiceReference.ListAccountsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListAccountsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ListAccountsRequestBody() {
        }
        
        public ListAccountsRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAccountsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAccountsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BankApplication.BankAppServiceReference.ListAccountsResponseBody Body;
        
        public ListAccountsResponse() {
        }
        
        public ListAccountsResponse(BankApplication.BankAppServiceReference.ListAccountsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListAccountsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankApplication.BankAppServiceReference.Hesap[] ListAccountsResult;
        
        public ListAccountsResponseBody() {
        }
        
        public ListAccountsResponseBody(BankApplication.BankAppServiceReference.Hesap[] ListAccountsResult) {
            this.ListAccountsResult = ListAccountsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BankWebServiceSoapChannel : BankApplication.BankAppServiceReference.BankWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankWebServiceSoapClient : System.ServiceModel.ClientBase<BankApplication.BankAppServiceReference.BankWebServiceSoap>, BankApplication.BankAppServiceReference.BankWebServiceSoap {
        
        public BankWebServiceSoapClient() {
        }
        
        public BankWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankApplication.BankAppServiceReference.AddCustomerResponse BankApplication.BankAppServiceReference.BankWebServiceSoap.AddCustomer(BankApplication.BankAppServiceReference.AddCustomerRequest request) {
            return base.Channel.AddCustomer(request);
        }
        
        public void AddCustomer(BankApplication.BankAppServiceReference.Musteri item) {
            BankApplication.BankAppServiceReference.AddCustomerRequest inValue = new BankApplication.BankAppServiceReference.AddCustomerRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.AddCustomerRequestBody();
            inValue.Body.item = item;
            BankApplication.BankAppServiceReference.AddCustomerResponse retVal = ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).AddCustomer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.AddCustomerResponse> BankApplication.BankAppServiceReference.BankWebServiceSoap.AddCustomerAsync(BankApplication.BankAppServiceReference.AddCustomerRequest request) {
            return base.Channel.AddCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.AddCustomerResponse> AddCustomerAsync(BankApplication.BankAppServiceReference.Musteri item) {
            BankApplication.BankAppServiceReference.AddCustomerRequest inValue = new BankApplication.BankAppServiceReference.AddCustomerRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.AddCustomerRequestBody();
            inValue.Body.item = item;
            return ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).AddCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankApplication.BankAppServiceReference.GetCustomerResponse BankApplication.BankAppServiceReference.BankWebServiceSoap.GetCustomer(BankApplication.BankAppServiceReference.GetCustomerRequest request) {
            return base.Channel.GetCustomer(request);
        }
        
        public BankApplication.BankAppServiceReference.Musteri GetCustomer(int id) {
            BankApplication.BankAppServiceReference.GetCustomerRequest inValue = new BankApplication.BankAppServiceReference.GetCustomerRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.GetCustomerRequestBody();
            inValue.Body.id = id;
            BankApplication.BankAppServiceReference.GetCustomerResponse retVal = ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).GetCustomer(inValue);
            return retVal.Body.GetCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.GetCustomerResponse> BankApplication.BankAppServiceReference.BankWebServiceSoap.GetCustomerAsync(BankApplication.BankAppServiceReference.GetCustomerRequest request) {
            return base.Channel.GetCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.GetCustomerResponse> GetCustomerAsync(int id) {
            BankApplication.BankAppServiceReference.GetCustomerRequest inValue = new BankApplication.BankAppServiceReference.GetCustomerRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.GetCustomerRequestBody();
            inValue.Body.id = id;
            return ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).GetCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankApplication.BankAppServiceReference.UpdateCustomerResponse BankApplication.BankAppServiceReference.BankWebServiceSoap.UpdateCustomer(BankApplication.BankAppServiceReference.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public void UpdateCustomer(BankApplication.BankAppServiceReference.Musteri item) {
            BankApplication.BankAppServiceReference.UpdateCustomerRequest inValue = new BankApplication.BankAppServiceReference.UpdateCustomerRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.UpdateCustomerRequestBody();
            inValue.Body.item = item;
            BankApplication.BankAppServiceReference.UpdateCustomerResponse retVal = ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).UpdateCustomer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.UpdateCustomerResponse> BankApplication.BankAppServiceReference.BankWebServiceSoap.UpdateCustomerAsync(BankApplication.BankAppServiceReference.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.UpdateCustomerResponse> UpdateCustomerAsync(BankApplication.BankAppServiceReference.Musteri item) {
            BankApplication.BankAppServiceReference.UpdateCustomerRequest inValue = new BankApplication.BankAppServiceReference.UpdateCustomerRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.UpdateCustomerRequestBody();
            inValue.Body.item = item;
            return ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).UpdateCustomerAsync(inValue);
        }
        
        public void DeleteCustomer(int id) {
            base.Channel.DeleteCustomer(id);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerAsync(int id) {
            return base.Channel.DeleteCustomerAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankApplication.BankAppServiceReference.LoginResponse BankApplication.BankAppServiceReference.BankWebServiceSoap.Login(BankApplication.BankAppServiceReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(string TcNumarasi, string Sifre) {
            BankApplication.BankAppServiceReference.LoginRequest inValue = new BankApplication.BankAppServiceReference.LoginRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.LoginRequestBody();
            inValue.Body.TcNumarasi = TcNumarasi;
            inValue.Body.Sifre = Sifre;
            BankApplication.BankAppServiceReference.LoginResponse retVal = ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.LoginResponse> BankApplication.BankAppServiceReference.BankWebServiceSoap.LoginAsync(BankApplication.BankAppServiceReference.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.LoginResponse> LoginAsync(string TcNumarasi, string Sifre) {
            BankApplication.BankAppServiceReference.LoginRequest inValue = new BankApplication.BankAppServiceReference.LoginRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.LoginRequestBody();
            inValue.Body.TcNumarasi = TcNumarasi;
            inValue.Body.Sifre = Sifre;
            return ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankApplication.BankAppServiceReference.OpenAccountResponse BankApplication.BankAppServiceReference.BankWebServiceSoap.OpenAccount(BankApplication.BankAppServiceReference.OpenAccountRequest request) {
            return base.Channel.OpenAccount(request);
        }
        
        public BankApplication.BankAppServiceReference.Hesap OpenAccount(int id) {
            BankApplication.BankAppServiceReference.OpenAccountRequest inValue = new BankApplication.BankAppServiceReference.OpenAccountRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.OpenAccountRequestBody();
            inValue.Body.id = id;
            BankApplication.BankAppServiceReference.OpenAccountResponse retVal = ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).OpenAccount(inValue);
            return retVal.Body.OpenAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.OpenAccountResponse> BankApplication.BankAppServiceReference.BankWebServiceSoap.OpenAccountAsync(BankApplication.BankAppServiceReference.OpenAccountRequest request) {
            return base.Channel.OpenAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.OpenAccountResponse> OpenAccountAsync(int id) {
            BankApplication.BankAppServiceReference.OpenAccountRequest inValue = new BankApplication.BankAppServiceReference.OpenAccountRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.OpenAccountRequestBody();
            inValue.Body.id = id;
            return ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).OpenAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankApplication.BankAppServiceReference.CloseAccountResponse BankApplication.BankAppServiceReference.BankWebServiceSoap.CloseAccount(BankApplication.BankAppServiceReference.CloseAccountRequest request) {
            return base.Channel.CloseAccount(request);
        }
        
        public void CloseAccount(int id, string hesapNumarasi) {
            BankApplication.BankAppServiceReference.CloseAccountRequest inValue = new BankApplication.BankAppServiceReference.CloseAccountRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.CloseAccountRequestBody();
            inValue.Body.id = id;
            inValue.Body.hesapNumarasi = hesapNumarasi;
            BankApplication.BankAppServiceReference.CloseAccountResponse retVal = ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).CloseAccount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.CloseAccountResponse> BankApplication.BankAppServiceReference.BankWebServiceSoap.CloseAccountAsync(BankApplication.BankAppServiceReference.CloseAccountRequest request) {
            return base.Channel.CloseAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.CloseAccountResponse> CloseAccountAsync(int id, string hesapNumarasi) {
            BankApplication.BankAppServiceReference.CloseAccountRequest inValue = new BankApplication.BankAppServiceReference.CloseAccountRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.CloseAccountRequestBody();
            inValue.Body.id = id;
            inValue.Body.hesapNumarasi = hesapNumarasi;
            return ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).CloseAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BankApplication.BankAppServiceReference.ListAccountsResponse BankApplication.BankAppServiceReference.BankWebServiceSoap.ListAccounts(BankApplication.BankAppServiceReference.ListAccountsRequest request) {
            return base.Channel.ListAccounts(request);
        }
        
        public BankApplication.BankAppServiceReference.Hesap[] ListAccounts(int id) {
            BankApplication.BankAppServiceReference.ListAccountsRequest inValue = new BankApplication.BankAppServiceReference.ListAccountsRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.ListAccountsRequestBody();
            inValue.Body.id = id;
            BankApplication.BankAppServiceReference.ListAccountsResponse retVal = ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).ListAccounts(inValue);
            return retVal.Body.ListAccountsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.ListAccountsResponse> BankApplication.BankAppServiceReference.BankWebServiceSoap.ListAccountsAsync(BankApplication.BankAppServiceReference.ListAccountsRequest request) {
            return base.Channel.ListAccountsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankApplication.BankAppServiceReference.ListAccountsResponse> ListAccountsAsync(int id) {
            BankApplication.BankAppServiceReference.ListAccountsRequest inValue = new BankApplication.BankAppServiceReference.ListAccountsRequest();
            inValue.Body = new BankApplication.BankAppServiceReference.ListAccountsRequestBody();
            inValue.Body.id = id;
            return ((BankApplication.BankAppServiceReference.BankWebServiceSoap)(this)).ListAccountsAsync(inValue);
        }
        
        public void SendTransfer() {
            base.Channel.SendTransfer();
        }
        
        public System.Threading.Tasks.Task SendTransferAsync() {
            return base.Channel.SendTransferAsync();
        }
        
        public void SendVirman() {
            base.Channel.SendVirman();
        }
        
        public System.Threading.Tasks.Task SendVirmanAsync() {
            return base.Channel.SendVirmanAsync();
        }
        
        public void GetCredit() {
            base.Channel.GetCredit();
        }
        
        public System.Threading.Tasks.Task GetCreditAsync() {
            return base.Channel.GetCreditAsync();
        }
        
        public int CreateNumber() {
            return base.Channel.CreateNumber();
        }
        
        public System.Threading.Tasks.Task<int> CreateNumberAsync() {
            return base.Channel.CreateNumberAsync();
        }
    }
}
